@baseUrl = http://localhost:5254

### Get all plans
GET {{baseUrl}}/api/plans
Accept: application/json


### Get plans overview
GET {{baseUrl}}/api/plans/overview
Accept: application/json


### Get days for a plan
@planId = 1
GET {{baseUrl}}/api/days/{{planId}}/days
Accept: application/json


### Get progress for a specific day
@day = 1
GET {{baseUrl}}/api/days/{{planId}}/days/{{day}}/progress
Accept: application/json


### Complete a day
POST {{baseUrl}}/api/days/completed
Content-Type: application/json

{
  "planId": 2,
  "dayId": 3,
  "completed": true
}

### Get today's workouts 
GET {{baseUrl}}/api/dashboard/today
Accept: application/json


###
GET {{baseUrl}}/api/Templates
Accept: application/json




###
POST {{baseUrl}}/api/sessions/start
Accept: application/json
Content-Type: application/json


1


###
GET {{baseUrl}}/api/sessions/2 
Accept: application/json


###
GET {{baseUrl}}/api/dashboard/week


### Update week planning (drag & drop)
PUT {{baseUrl}}/api/dashboard/week
Content-Type: application/json

{
  "id": 3,
  "dayOfWeek": 4
}

